name: Docker Image CI

env:
  IMAGE_NAME: linux-dev-tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:$(date +%s)
