name: Docker Image CI

env:
  DOCKER_REPO: macp
  IMAGE_NAME: linux-dev-tools
  IMAGE_VERSION: latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:${IMAGE_VERSION}
    - name: Deploy the Docker image
      run: docker tag ${IMAGE_NAME}:${IMAGE_VERSION} ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_VERSION}

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push the Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:$(date +%s)

